"use client";
import {ChangeEvent,type CSSProperties,useEffect,useRef,useState} from "react";
import {useParams} from "next/navigation";
import {TravelHero} from "@/components/travel-hero";
import {PhotoLightbox} from "@/components/photo-lightbox";
import {drivePreviewUrl} from "@/lib/travel/image-url";
import {appendPlanPhotos,deletePlanPhoto,getPlanById,listPlanPhotos,setPlanCoverPhoto,type TravelPlanPhotoRow,type TravelPlanRow} from "@/lib/travel/repository";
import {uploadTravelPhotos} from "@/lib/travel/uploads";
function PlusIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>}
function TrashIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3m-8 0 1 13h8l1-13M10 11v5m4-5v5"/></svg>}
const t={travel:"\u0e41\u0e1c\u0e19\u0e01\u0e32\u0e23\u0e40\u0e14\u0e34\u0e19\u0e17\u0e32\u0e07",photos:"\u0e23\u0e39\u0e1b\u0e20\u0e32\u0e1e\u0e41\u0e1c\u0e19\u0e01\u0e32\u0e23\u0e40\u0e14\u0e34\u0e19\u0e17\u0e32\u0e07",pic:"\u0e23\u0e39\u0e1b",cover:"\u0e23\u0e39\u0e1b\u0e2b\u0e19\u0e49\u0e32\u0e1b\u0e01",setCover:"\u0e15\u0e31\u0e49\u0e07\u0e23\u0e39\u0e1b\u0e2b\u0e19\u0e49\u0e32\u0e1b\u0e01",add:"\u0e40\u0e1e\u0e34\u0e48\u0e21\u0e23\u0e39\u0e1b",upload:"\u0e01\u0e33\u0e25\u0e31\u0e07\u0e2d\u0e31\u0e1b\u0e42\u0e2b\u0e25\u0e14",done:"\u0e2d\u0e31\u0e1b\u0e42\u0e2b\u0e25\u0e14\u0e40\u0e2a\u0e23\u0e47\u0e08\u0e41\u0e25\u0e49\u0e27",detail:"\u0e23\u0e32\u0e22\u0e25\u0e30\u0e40\u0e2d\u0e35\u0e22\u0e14\u0e41\u0e1c\u0e19",empty:"\u0e22\u0e31\u0e07\u0e44\u0e21\u0e48\u0e21\u0e35\u0e23\u0e32\u0e22\u0e25\u0e30\u0e40\u0e2d\u0e35\u0e22\u0e14",loading:"\u0e01\u0e33\u0e25\u0e31\u0e07\u0e42\u0e2b\u0e25\u0e14..."};
function formatDate(v:string|null){return v?new Intl.DateTimeFormat("th-TH",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${v}T00:00:00`)):"-"}
export default function PlanDetailPage(){const {id}=useParams<{id:string}>();const inputRef=useRef<HTMLInputElement>(null);const [plan,setPlan]=useState<TravelPlanRow|null>(null);const [photos,setPhotos]=useState<TravelPlanPhotoRow[]>([]);const [selected,setSelected]=useState<string|null>(null);const [lightbox,setLightbox]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [progress,setProgress]=useState<{done:number;total:number}|null>(null);
async function reload(){const [p,ph]=await Promise.all([getPlanById(id),listPlanPhotos(id)]);setPlan(p);setPhotos(ph)}
useEffect(()=>{let active=true;Promise.all([getPlanById(id),listPlanPhotos(id)]).then(([p,ph])=>{if(active){setPlan(p);setPhotos(ph)}}).catch((e:unknown)=>active&&setMessage(e instanceof Error?e.message:"Load failed"));return()=>{active=false}},[id]);
async function addPhotos(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files??[]).filter(f=>f.type.startsWith("image/"));e.target.value="";if(!files.length||busy)return;setBusy(true);setProgress({done:0,total:files.length});try{const up=await uploadTravelPhotos(files,id,(done,total)=>setProgress({done,total}),plan?.title||"travel-plan");await appendPlanPhotos(id,up);await reload();setMessage(`${t.add} ${up.length} ${t.pic}`)}catch(err){setMessage(err instanceof Error?err.message:"Upload failed")}finally{setBusy(false);window.setTimeout(()=>setProgress(null),1200)}}
async function makeCover(photo:TravelPlanPhotoRow){if(busy||photo.is_cover)return;setBusy(true);try{await setPlanCoverPhoto(id,photo);await reload();setSelected(null)}catch(e){setMessage(e instanceof Error?e.message:"Cover failed")}finally{setBusy(false)}}
async function removePhoto(photo:TravelPlanPhotoRow){if(busy||!window.confirm("Delete this photo?"))return;setBusy(true);try{await deletePlanPhoto(id,photo);await reload()}catch(e){setMessage(e instanceof Error?e.message:"Delete failed")}finally{setBusy(false)}}
if(!plan)return <p className="loading-page">{message||t.loading}</p>;
return <main><TravelHero title={plan.title} subtitle={plan.province||plan.location_name||t.travel} backHref="/plans" editable editHref={`/plans/${id}/edit`}/><section className="content place-detail-content"><section className="card place-photo-card"><div className="card-title-row"><h2>{t.photos}</h2><small>{photos.length} {t.pic}</small></div><input ref={inputRef} hidden type="file" accept="image/*" multiple capture="environment" onChange={addPhotos}/><div className="detail-photo-grid">{photos.map((photo,index)=><article key={photo.id} className={`detail-photo-tile${selected===photo.id?" selected":""}`}><button type="button" className="detail-photo-select" onClick={()=>setLightbox(index)}><img src={drivePreviewUrl(photo.drive_file_id,photo.thumbnail_url||photo.drive_url,480)} alt={`${plan.title} ${index+1}`} loading={index===0?"eager":"lazy"}/></button><button type="button" className="photo-trash-button" disabled={busy} onClick={()=>void removePhoto(photo)} aria-label="Delete photo"><TrashIcon/></button>{photo.is_cover?<span className="cover-status-badge">{t.cover}</span>:<><button type="button" className={`cover-choice-button${selected===photo.id?" active":""}`} onClick={()=>setSelected(c=>c===photo.id?null:photo.id)}>☆</button>{selected===photo.id&&<button type="button" className="set-cover-button" disabled={busy} onClick={()=>void makeCover(photo)}>{t.setCover}</button>}</>}</article>)}<button type="button" className="add-photo-tile" disabled={busy} onClick={()=>inputRef.current?.click()}><span><PlusIcon/></span><small>{busy?t.upload:t.add}</small></button></div>{progress&&<div className="upload-gauge-panel"><div className="upload-gauge" style={{"--upload-progress":`${Math.round(progress.done/Math.max(progress.total,1)*100)}%`} as CSSProperties}><span>{Math.round(progress.done/Math.max(progress.total,1)*100)}%</span></div><div className="upload-gauge-copy"><strong>{busy?t.upload:t.done}</strong><span>{progress.done} / {progress.total} {t.pic}</span></div></div>}{message&&<p className="detail-photo-message">{message}</p>}</section><section className="card detail-info-card"><h2>{t.detail}</h2><p>{plan.note||t.empty}</p><p>📅 {formatDate(plan.start_date)} – {formatDate(plan.end_date)}</p><p>💰 {new Intl.NumberFormat("th-TH").format(plan.budget||0)} บาท</p><p>⌖ {[plan.subdistrict,plan.district,plan.province].filter(Boolean).join(" · ")||plan.location_name}</p></section></section>{lightbox!==null&&<PhotoLightbox photos={photos} index={lightbox} onClose={()=>setLightbox(null)}/>}</main>}
