"use client";
import { useEffect, useRef, useState } from "react";
export type LocationValue={latitude:string;longitude:string;locationName:string;subdistrict:string;district:string;province:string};
type SearchItem=LocationValue&{id:string;name:string;address:string};
type Props={value:LocationValue;onChange:(value:LocationValue)=>void;onSelectName?:(name:string)=>void};
type LeafletMap={setView:(coords:[number,number],zoom:number)=>LeafletMap;invalidateSize:()=>void;on:(event:string,handler:(event:{latlng:{lat:number;lng:number}})=>void)=>void;remove:()=>void};
type LeafletMarker={addTo:(map:LeafletMap)=>LeafletMarker;setLatLng:(coords:[number,number])=>LeafletMarker;on:(event:string,handler:(event:{target:{getLatLng:()=>{lat:number;lng:number}}})=>void)=>void};
type LeafletApi={map:(element:HTMLElement,options?:Record<string,unknown>)=>LeafletMap;tileLayer:(url:string,options:Record<string,unknown>)=>{addTo:(map:LeafletMap)=>void};marker:(coords:[number,number],options?:Record<string,unknown>)=>LeafletMarker};
declare global{interface Window{L?:LeafletApi}}
const DEFAULT:[number,number]=[13.7563,100.5018];
function loadLeaflet():Promise<LeafletApi>{if(window.L)return Promise.resolve(window.L);return new Promise((resolve,reject)=>{if(!document.querySelector('link[data-leaflet]')){const link=document.createElement("link");link.rel="stylesheet";link.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";link.dataset.leaflet="1";document.head.appendChild(link)}const existing=document.querySelector<HTMLScriptElement>('script[data-leaflet]');if(existing){existing.addEventListener("load",()=>window.L?resolve(window.L):reject(new Error("Leaflet unavailable")),{once:true});return}const script=document.createElement("script");script.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";script.dataset.leaflet="1";script.onload=()=>window.L?resolve(window.L):reject(new Error("Leaflet unavailable"));script.onerror=()=>reject(new Error("โหลดแผนที่ไม่สำเร็จ"));document.body.appendChild(script)})}
export function LocationPicker({value,onChange,onSelectName}:Props){const mapEl=useRef<HTMLDivElement>(null),mapRef=useRef<LeafletMap|null>(null),markerRef=useRef<LeafletMarker|null>(null),valueRef=useRef(value),onChangeRef=useRef(onChange);const[query,setQuery]=useState(""),[items,setItems]=useState<SearchItem[]>([]),[loading,setLoading]=useState(false),[mapError,setMapError]=useState("");valueRef.current=value;onChangeRef.current=onChange;
useEffect(()=>{let alive=true;loadLeaflet().then(L=>{if(!alive||!mapEl.current||mapRef.current)return;const lat=Number(valueRef.current.latitude),lng=Number(valueRef.current.longitude),coords:[number,number]=Number.isFinite(lat)&&Number.isFinite(lng)?[lat,lng]:DEFAULT;const map=L.map(mapEl.current,{zoomControl:true}).setView(coords,Number.isFinite(lat)?15:6);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:'&copy; OpenStreetMap contributors',maxZoom:19}).addTo(map);const marker=L.marker(coords,{draggable:true}).addTo(map);const apply=(a:number,b:number)=>{const next={...valueRef.current,latitude:a.toFixed(6),longitude:b.toFixed(6)};onChangeRef.current(next);void reverse(a,b,next)};map.on("click",e=>{marker.setLatLng([e.latlng.lat,e.latlng.lng]);apply(e.latlng.lat,e.latlng.lng)});marker.on("dragend",e=>{const p=e.target.getLatLng();apply(p.lat,p.lng)});mapRef.current=map;markerRef.current=marker;window.setTimeout(()=>map.invalidateSize(),120)}).catch(e=>alive&&setMapError(e instanceof Error?e.message:"โหลดแผนที่ไม่สำเร็จ"));return()=>{alive=false;mapRef.current?.remove();mapRef.current=null;markerRef.current=null}},[]);
useEffect(()=>{const lat=Number(value.latitude),lng=Number(value.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng)||!mapRef.current||!markerRef.current)return;markerRef.current.setLatLng([lat,lng]);mapRef.current.setView([lat,lng],15);window.setTimeout(()=>mapRef.current?.invalidateSize(),60)},[value.latitude,value.longitude]);
useEffect(()=>{const q=query.trim();if(q.length<2)return;const controller=new AbortController();const timer=window.setTimeout(()=>{setLoading(true);fetch(`/api/geocode?q=${encodeURIComponent(q)}`,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<{results?:SearchItem[]}>}).then(d=>setItems(d.results??[])).catch(e=>{if(e instanceof Error&&e.name==="AbortError")return;setItems([])}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})},500);return()=>{clearTimeout(timer);controller.abort()}},[query]);
async function reverse(lat:number,lng:number,fallback:LocationValue){try{const r=await fetch(`/api/geocode?mode=reverse&lat=${lat}&lon=${lng}`);const d=await r.json() as {result?:LocationValue};onChangeRef.current(d.result??fallback)}catch{onChangeRef.current(fallback)}}
function choose(i:SearchItem){const next={latitude:i.latitude,longitude:i.longitude,locationName:i.locationName,subdistrict:i.subdistrict,district:i.district,province:i.province};onChange(next);onSelectName?.(i.name);setQuery(i.name);setItems([]);const lat=Number(i.latitude),lng=Number(i.longitude);if(Number.isFinite(lat)&&Number.isFinite(lng)){markerRef.current?.setLatLng([lat,lng]);mapRef.current?.setView([lat,lng],16)}}
function useGps(){if(!navigator.geolocation){setMapError("อุปกรณ์นี้ไม่รองรับ GPS");return}navigator.geolocation.getCurrentPosition(p=>{const lat=p.coords.latitude,lng=p.coords.longitude,next={...valueRef.current,latitude:lat.toFixed(6),longitude:lng.toFixed(6)};onChange(next);markerRef.current?.setLatLng([lat,lng]);mapRef.current?.setView([lat,lng],17);void reverse(lat,lng,next)},()=>setMapError("ไม่สามารถอ่านตำแหน่งได้ กรุณาอนุญาตการเข้าถึงตำแหน่ง"),{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
return <div className="location-picker"><div ref={mapEl} className="leaflet-map" aria-label="แผนที่เลือกตำแหน่ง"/>{mapError&&<p className="map-error">{mapError}</p>}<p className="map-attribution-note">แตะแผนที่หรือลากหมุดเพื่อเลือกพิกัด</p><label className="full location-search-label">ค้นหาสถานที่<input className="location-search-input" value={query} onChange={e=>{const n=e.target.value;setQuery(n);if(n.trim().length<2){setItems([]);setLoading(false)}}} placeholder="ชื่อสถานที่ ตำบล อำเภอ จังหวัด" autoComplete="off"/></label>{loading&&<p className="hint">กำลังค้นหา…</p>}{items.length>0&&<div className="search-results">{items.map(i=><button type="button" key={i.id} onClick={()=>choose(i)}><strong>{i.name}</strong><span>{i.address}</span></button>)}</div>}<button type="button" className="secondary gps-button" onClick={useGps}>◎ ใช้ตำแหน่งปัจจุบัน</button><div className="form-grid"><label>ละติจูด<input inputMode="decimal" value={value.latitude} onChange={e=>onChange({...value,latitude:e.target.value})}/></label><label>ลองจิจูด<input inputMode="decimal" value={value.longitude} onChange={e=>onChange({...value,longitude:e.target.value})}/></label><label className="full">ชื่อสถานที่/ที่อยู่<input value={value.locationName} onChange={e=>onChange({...value,locationName:e.target.value})}/></label><label>ตำบล<input value={value.subdistrict} onChange={e=>onChange({...value,subdistrict:e.target.value})}/></label><label>อำเภอ<input value={value.district} onChange={e=>onChange({...value,district:e.target.value})}/></label><label className="full">จังหวัด<input value={value.province} onChange={e=>onChange({...value,province:e.target.value})}/></label></div></div>}
